export const sedesCentros = [
    {
        id: 1,
        nombre: "Colegio E. Bethesda",
        telefono: "(809) 534-1266",
        direccion: "C21 No.1, Ens. Rosa, Las Palmas Herrera, SD",
        director: "Cleta Rosario",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/cBmOiyFtp0QPnWXHs",
        provincia: "Santo Domingo",
        coords: [18.4728, -69.9822]
    },
    {
        id: 2,
        nombre: "Colegio E. Emanuel",
        telefono: "(809) 545-2233",
        direccion: "Duarte 210, Sávica,Los Alcarrizos, SD",
        director: "Arelis Morel",
        codigo: "1168316",
        distrito: "1501",
        matricula: "",
        aulas: "",
        ubicacion: "https://maps.google.com/?q=18.519445,-69.844894",
        provincia: "Santo Domingo",
        coords: [18.519445, -69.844894]
    },
    {
        id: 3,
        nombre: "Colegio E. Dulce Corporal",
        telefono: "(809) 564-8376",
        direccion: "Calle 23 No. 58, Los Alcarrizos, SD",
        director: "Pablo González",
        codigo: "1170010",
        distrito: "1501",
        matricula: "",
        aulas: "",
        ubicacion: "https://maps.app.goo.gl/B6VaSRUKGjYDwDvd9?g_st=iw",
        provincia: "Santo Domingo",
        coords: [18.515, -70.015]
    },
    {
        id: 4,
        nombre: "Colegio E. Marcelina Dawson",
        telefono: "(809) 701-7623",
        direccion: "Calle primera No. 58, Los Alcarrizos, SD",
        director: "Luz Isania Alcántara",
        codigo: "1166014",
        distrito: "1501",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/JU82OW7N6pmIN9rFi",
        provincia: "Santo Domingo",
        coords: [18.517, -70.016]
    },
    {
        id: 5,
        nombre: "Centro de Estudio Fuente de Luz",
        telefono: "(809) 483- 0147",
        direccion: "Calle Central No. 77, Urb. Lucerna, SD",
        director: "Margarita de Parra",
        codigo: "32008710",
        distrito: "1505",
        matricula: "130",
        aulas: "11",
        ubicacion: "https://share.google/wuR3X3wYj2niiwIIM",
        provincia: "Santo Domingo",
        coords: [18.502, -69.835]
    },
    {
        id: 6,
        nombre: "Centro de Estudios Peniel",
        telefono: "(809) 530-9290",
        direccion: "Central No. 6, Ens. La Alt, Herrera, SD",
        director: "Seferina Raposo",
        codigo: "113918",
        distrito: "1505",
        matricula: "998",
        aulas: "19",
        ubicacion: "https://share.google/pp3CqC5tu3aWaGMgu",
        provincia: "Santo Domingo",
        coords: [18.475, -69.985]
    },
    {
        id: 7,
        nombre: "Colegio E. La Trinidad",
        telefono: "(809) 363-1476",
        direccion: "Calle 12 No. 33, Ens. Quisqueya, SD",
        director: "Jhonnatha Barriento",
        codigo: "1034019",
        distrito: "1503",
        matricula: "259",
        aulas: "14",
        ubicacion: "https://share.google/CIpYWMKl54ycNZ3Wv",
        provincia: "Distrito Nacional",
        coords: [18.472, -69.94]
    },
    {
        id: 8,
        nombre: "Colegio Adonai",
        telefono: "(809) 239-0939",
        direccion: "Anacaona No.52,Centro Guaricamo, SD",
        director: "Tomasina Rodríguez S",
        codigo: "1157711",
        distrito: "1001",
        matricula: "389",
        aulas: "16",
        ubicacion: "https://share.google/FmftpuKn3wfn57mRU",
        provincia: "Santo Domingo",
        coords: [18.56, -69.912]
    },
    {
        id: 9,
        nombre: "Colegio 5 panes y 2 peces",
        telefono: "(809) 222-1648",
        direccion: "C. Duarte No.26,Esq. G.Luperon, S Isidro, SD",
        director: "Ramón Reynoso Almonte",
        codigo: "32031615",
        distrito: "1003",
        matricula: "417",
        aulas: "12 / 2 t.",
        ubicacion: "https://share.google/Pcuykpmw0M1Zi4idR",
        provincia: "Santo Domingo",
        coords: [18.514, -69.774]
    },
    {
        id: 10,
        nombre: "Colegio Cristiano Riobisa",
        telefono: "(809) 569-6982",
        direccion: "C.Principal No. 12,El Edén,Villa Mella, SD",
        director: "Crecencia Morel",
        codigo: "3012410",
        distrito: "1001",
        matricula: "271",
        aulas: "20",
        ubicacion: "https://share.google/Jv26mF2WBP6guEaaf",
        provincia: "Santo Domingo",
        coords: [18.544, -69.904]
    },
    {
        id: 11,
        nombre: "Colegio Los Olivitos(N. Renacer)",
        telefono: "(849) 295-5847",
        direccion: "Nicolás Brazoban 12, Casa Vieja,Villa Mella, SD",
        director: "María García Valdez",
        codigo: "11707",
        distrito: "1001",
        matricula: "100",
        aulas: "7",
        ubicacion: "https://share.google/P978gZ3bxAdaP7lkq",
        provincia: "Santo Domingo",
        coords: [18.546, -69.906]
    },
    {
        id: 12,
        nombre: "Colegio Mi Esperanza",
        telefono: "(809) 239-5908",
        direccion: "H.Mirabal No 4, B. Enriquillo, Sab. Perdida, SD",
        director: "Elizabeth Ramirez",
        codigo: "9688",
        distrito: "1008",
        matricula: "117",
        aulas: "10",
        ubicacion: "https://share.google/Nd2pRFm54JDKU4Abr",
        provincia: "Santo Domingo",
        coords: [18.529, -69.873]
    },
    {
        id: 13,
        nombre: "Colegio E. Ebenezer",
        telefono: "(809) 957-0374",
        direccion: "Francisco de la Concha No. 11, Haina",
        director: "Ana de Jesús Graciano",
        codigo: "217010",
        distrito: "406",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/FJA2BAyn8D6rPkYLB",
        provincia: "San Cristóbal",
        coords: [18.419, -70.035]
    },
    {
        id: 14,
        nombre: "Colegio E. San Pablo",
        telefono: "(809) 559-2490",
        direccion: "C. 29 de Abril No. 17, Villa Altagracia",
        director: "Brigida Casilla",
        codigo: "7952",
        distrito: "404",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/YShVQ0rnw3x79fvfk",
        provincia: "San Cristóbal",
        coords: [18.775, -70.165]
    },
    {
        id: 15,
        nombre: "Colegio E. Emanuel",
        telefono: "(809) 522-8332",
        direccion: "C. Santome Esq. Máximo Gómez, Bani",
        director: "Cristobalina de Kelly",
        codigo: "17004716",
        distrito: "304",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/MyQws17rPamdPJZia",
        provincia: "Peravia",
        coords: [18.279, -70.332]
    },
    {
        id: 16,
        nombre: "Colegio E. Puertas Abiertas",
        telefono: "(809) 380-7174",
        direccion: "Toribio Mejia 51, Villa Rosa, Bani",
        director: "Elen Furment",
        codigo: "13249",
        distrito: "304",
        matricula: "125",
        aulas: "3    2t.",
        ubicacion: "https://share.google/50M2meBArNBHtF19W",
        provincia: "Peravia",
        coords: [18.281, -70.334]
    },
    {
        id: 17,
        nombre: "Colegio E. Sinaí",
        telefono: "(809) 556-4874",
        direccion: "Santa Rosa Esq.Eugenio A.Miranda, La Romana",
        director: "Amancia Gabriel",
        codigo: "7005",
        distrito: "503",
        matricula: "825",
        aulas: "32",
        ubicacion: "https://share.google/rEEkADruKpu5LVMWo",
        provincia: "La Romana",
        coords: [18.427, -68.973]
    },
    {
        id: 18,
        nombre: "Colegio Piedra del Angulo",
        telefono: "(809) 223-1534",
        direccion: "C.17 No. 20, Pica Piedra, V. Hermosa La Romana",
        director: "Dilenia Félix",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/50M2meBArNBHtF19W",
        provincia: "La Romana",
        coords: [18.435, -68.985]
    },
    {
        id: 19,
        nombre: "Colegio E. Efraín",
        telefono: "(809) 575-1842",
        direccion: "Calle Primera No. 14 Ens. Ramos, Santiago",
        director: "Altagracia Billini",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://maps.app.goo.gl/2xtEmc455SkbMWVF6?g_st=aw",
        provincia: "Santiago",
        coords: [19.452, -70.697]
    },
    {
        id: 20,
        nombre: "Colegio E. Elohim",
        telefono: "(809) 581-9346",
        direccion: "Prol. San José, Santiago",
        director: "Félix Díaz",
        codigo: "25008719",
        distrito: "805",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/SIZKENnkXWqtLGbqO",
        provincia: "Santiago",
        coords: [19.455, -70.699]
    },
    {
        id: 21,
        nombre: "Colegio Cristiana la Vega",
        telefono: "(809) 573-3033",
        direccion: "Calle Joaquin Gomez, La Vega",
        director: "Adalgisa Santana",
        codigo: "13054017",
        distrito: "604",
        matricula: "301",
        aulas: "21",
        ubicacion: "https://share.google/MXGs2clhuWMyZMYSi",
        provincia: "La Vega",
        coords: [19.22, -70.53]
    },
    {
        id: 22,
        nombre: "Colegio E. Bethel",
        telefono: "(809) 586- 5273",
        direccion: "Calle Villanueva No. 65, Puerto Plata",
        director: "Hilda Belliard",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/qPkAc8Dql3torSf3n",
        provincia: "Puerto Plata",
        coords: [19.793, -70.688]
    },
    {
        id: 23,
        nombre: "Colegio E. Elsa de Salcie",
        telefono: "(809) 587-0869",
        direccion: "C. Mella No. 13, Sector Buenos Aires, Villa Rivas",
        director: "Yenny Taveras",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/qPkAc8Dql3torSf3n",
        provincia: "Duarte",
        coords: [19.184, -69.872]
    },
    {
        id: 24,
        nombre: "Colegio E. Jerusalém",
        telefono: "(809) 529-6845",
        direccion: "Calle Municipal, San Pedro Macoris",
        director: "Ana Iris Benitez",
        codigo: "8243",
        distrito: "501",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/MXoggmFMJNqmXIC2a",
        provincia: "San Pedro de Macorís",
        coords: [18.452, -69.3]
    },
    {
        id: 25,
        nombre: "Colegio E. Alfaro",
        telefono: "(809) 354-3354",
        direccion: "Calle Jazmín ·19, Las Flores, San Cristobal",
        director: "María Mercedes de la Cruz",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/g32aoE3RR3w6wVTt0",
        provincia: "San Cristóbal",
        coords: [18.416, -70.108]
    },
    {
        id: 26,
        nombre: "Colegio E. Esmirna",
        telefono: "(809) 524-0292",
        direccion: "PEDERNALES",
        director: "Sonia Ramírez",
        codigo: "87428",
        distrito: "101",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/C0AxkYJbFLcao0Gcc",
        provincia: "Pedernales",
        coords: [18.038, -71.744]
    },
    {
        id: 27,
        nombre: "Colegio Shadai",
        telefono: "(809) 399-1886",
        direccion: "Dirección Sabaneta de San Juan",
        director: "Ruth I. Tavera",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/aimode/x34VFSTPFA2n6sjML",
        provincia: "San Juan",
        coords: [18.81, -71.229]
    },
    {
        id: 28,
        nombre: "Colegio E. Bethel",
        telefono: "(809) 578-0872",
        direccion: "Calle Antonio de la Masa No. 50, Moca",
        director: "",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/Jo4mVXhOrX91XIvPv",
        provincia: "Espaillat",
        coords: [19.394, -70.526]
    },
    {
        id: 29,
        nombre: "Colegio E. Siloė",
        telefono: "(809) 578-0872",
        direccion: "Las Matas de Farfan",
        director: "Fernely Aquino",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/WusXCpSKJU9CpZC6t",
        provincia: "San Juan",
        coords: [18.772, -71.517]
    },
    {
        id: 30,
        nombre: "Colegio E. Génesis",
        telefono: "(809) 554-0329",
        direccion: "Calle Eliseo Pérez No. 27, Higuey",
        director: "Tamaris Calderón",
        codigo: "11001619",
        distrito: "1201",
        matricula: "400",
        aulas: "11",
        ubicacion: "https://share.google/O53fyL8Bsw8yAsebq",
        provincia: "La Altagracia",
        coords: [18.615, -68.704]
    },
    {
        id: 31,
        nombre: "Colegio E. Betuel",
        telefono: "(809) 551-0676",
        direccion: "Sector Los Martínez, La Otra Banda, Higuey",
        director: "Floralba Tapia",
        codigo: "1101214",
        distrito: "1201",
        matricula: "242",
        aulas: "10",
        ubicacion: "https://share.google/XQhVzsT1pNybHkTTu",
        provincia: "La Altagracia",
        coords: [18.625, -68.65]
    },
    {
        id: 32,
        nombre: "Colegio E. Socrro de lo Alto",
        telefono: "(809) 388-6405",
        direccion: "Manzana A No.1, Catanga Los Mina",
        director: "Rosafina Perez",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/Pxmouu8vtP4JRy275",
        provincia: "Santo Domingo",
        coords: [18.497, -69.851]
    },
    {
        id: 33,
        nombre: "Proyecto Cristiano Fluir de Alegria",
        telefono: "(809) 459-1103",
        direccion: "Calle principal S/N, Barrio Chino, Villa Altagracia",
        director: "Martina Lorenzo",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/GLRoSEakEA4c1MqjN",
        provincia: "San Cristóbal",
        coords: [18.78, -70.17]
    },
    {
        id: 34,
        nombre: "Comunidad Infantil de Desarrollo Integral",
        telefono: "(809) 764-4030",
        direccion: "Calle Salome Ureña No. 10, La Espernza, Sto Dgo Norte",
        director: "Pastora= Rafaela Martinez",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/4t4F2sqjV1TRjryfd",
        provincia: "Santo Domingo",
        coords: [18.535, -69.88]
    },
    {
        id: 35,
        nombre: "Centro de Desarrollo Integral para la Niñez",
        telefono: "(809) 914-0579",
        direccion: "C/Sanchez #50 Comendador, Elias Piña",
        director: "Santa Diroche Rosario",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/A2HSuhx77OVVuFaN4",
        provincia: "Elías Piña",
        coords: [18.879, -71.703]
    },
    {
        id: 36,
        nombre: "Colegio Cristiano Arboles de Vida",
        telefono: "(809) 620-9826",
        direccion: "Villa Aura, Sto Dgo.",
        director: "Reyna Cuevas",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/cDxRXuqtlFDP9qsR3",
        provincia: "Santo Domingo",
        coords: [18.484, -69.991]
    },
    {
        id: 37,
        nombre: "Colegio Jardin de Dios",
        telefono: "(809) 372-0411",
        direccion: "Los jardines del Norte",
        director: "Blanca Margarita Martinez",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/MrF4B00NF8YUBBw4i",
        provincia: "Distrito Nacional",
        coords: [18.487, -69.947]
    },
    {
        id: 38,
        nombre: "Montessani Manaen",
        telefono: "(809) 560-5993",
        direccion: "C/ Penetracion #38 A, Residencial Amapola",
        director: "Alexis Encarnacion",
        codigo: "",
        distrito: "",
        matricula: "",
        aulas: "",
        ubicacion: "https://share.google/bjXJiIjkAmNhMTj8M",
        provincia: "Santo Domingo",
        coords: [18.489, -69.821]
    }
];
